###
:save_user_to_postgres_endpoint = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewUser
POST :save_user_to_postgres_endpoint
Accept-Encoding: application/json
Content-Type: application/json

{
 "userId": "3b30e3d5-158a-4670-b6b8-7ffc328dcac5",
 "email": "squirtle@somemail.io",
 "name": "Squirtle"
}
#
:save_study_to_postgres_endpoint = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewStudy
POST :save_study_to_postgres_endpoint
Accept-Encoding: application/json
Content-Type: application/json

{
 "userId": "3b30e3d5-158a-4670-b6b8-7ffc328dcac5",
 "title": "Sea Bass Fish Count",
 "protocolVersion": "1.0",
 "studyId": "42eac5cb-0885-40a4-8010-16fb5246d8c8"
}
#
:authorize_user_for_study_endpoint = https://us-central1-nyc-tlc-1225.cloudfunctions.net/addSurveyorToStudy
POST :authorize_user_for_study_endpoint
Accept-Encoding: application/json
Content-Type: application/json

{
 "userEmail": "squirtle@somemail.io",
 "studyId": "42eac5cb-0885-40a4-8010-16fb5246d8c8"
}
#
:create_new_survey = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewSurvey
POST :create_new_survey
Accept-Encoding: application/json
Content-Type: application/json

{
 "studyId": "42eac5cb-0885-40a4-8010-16fb5246d8c8",
 "surveyId": "17f32eae-01c5-463c-aabf-686de95607bf",
 "startDate": "2018-09-14T17:00:00Z",
 "endDate": "2018-09-14T19:00:00Z",
 "representation": "absolute",
 "method": "analog",
 "userId": "3b30e3d5-158a-4670-b6b8-7ffc328dcac5"
}
#
