:adminEmail = "sebastian@sidewalklabs.com"
:adminUserId = "3b30e3d5-158a-4670-b6b8-7ffc328dcac5"

:studyId = "42eac5cb-0885-40a4-8010-16fb5246d8c8"
:surveyId = "17f32eae-01c5-463c-aabf-686de95607bf"

:dataCollectorId = "7566b7ca-0372-46c6-9d2c-0e9fb38bebfb"
:dataCollectorEmail = "thorncliffeparkpubliclifepilot@gmail.com"

#
:save_user_to_postgres_endpoint = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewUser
POST :save_user_to_postgres_endpoint
Accept-Encoding: application/json
Content-Type: application/json

{
 "userId": :adminUserId,
 "email": :adminEmail,
 "name": "Seabreezy"
}
#
:save_user_to_postgres_endpoint = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewUser
POST :save_user_to_postgres_endpoint
Accept-Encoding: application/json
Content-Type: application/json

{
 "userId": :dataCollectorId,
 "email": :dataCollectorEmail,
 "name": "Thorncliffe park data colllector"
}
#
:studyTitle = "Sea Bass Fish Count"
:save_study_to_postgres_endpoint = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewStudy
POST :save_study_to_postgres_endpoint
Accept-Encoding: application/json
Content-Type: application/json

{
 "userId": :adminUserId,
 "title": "Stationary Counts RV Burgess",
 "protocolVersion": "1.0",
 "studyId": :studyId
}
#
:authorize_user_for_study_endpoint = https://us-central1-nyc-tlc-1225.cloudfunctions.net/addSurveyorToStudy
POST :authorize_user_for_study_endpoint
Accept-Encoding: application/json
Content-Type: application/json

{
 "userEmail": :dataCollectorEmail,
 "studyId": :studyId
}
#
:create_new_survey = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewSurvey
POST :create_new_survey
Accept-Encoding: application/json
Content-Type: application/json

{
 "studyId": :studyId,
 "locationId": "ab91643b-3bd5-41f5-a9ab-a59e9a20bfe7",
 "surveyId": :surveyId,
 "startDate": "2018-09-14T17:00:00Z",
 "endDate": "2018-09-14T19:00:00Z",
 "representation": "absolute",
 "method": "analog",
 "userId": :dataCollectorId
}
#
:create_new_location = https://us-central1-nyc-tlc-1225.cloudfunctions.net/saveNewLocation
POST :create_new_location
Accept-Encoding: application/json
Content-Type: application/json

{
    "locationId": "07ab155a-2b38-44a7-ad73-b6711b3d46b9",
    "country": "Canada",
    "city": "Toronto",
    "namePrimary": "Zone 3",
    "subdivision": "west",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                -79.34435606002809,
                43.70395407191628
            ],
            [
                -79.34425145387651,
                43.70387845004543
            ],
            [
                -79.34404492378236,
                43.70362637645357
            ],
            [
                -79.3438357114792,
                43.70356820547418
            ],
            [
                -79.34322685003282,
                43.703548815135164
            ],
            [
                -79.34306591749193,
                43.70346931467964
            ],
            [
                -79.3434950709343,
                43.70313967751972
            ],
            [
                -79.34463769197465,
                43.70377955976265
            ]
        ]
    }
}
#